##
## Build
##

FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY *.go ./

RUN go build -o /dockergo
# sometimes you'll see /go/bin/dockergo used. Anything will work as we will
# inject the artifact into a scratch (empty )container

##
## Deploy
##

# a "scratch" container is an "empty" container
FROM scratch

WORKDIR /

COPY --from=build /dockergo /dockergo

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/dockergo"]
